function lambda=tf_expand_scaling_trap_off_modv1_sph_approx(omega_tzero,t)


omega_rad=sqrt(mean(omega_tzero.^2));
% latex version
% -\frac{5}{12 \left(t^2 \text{$\omega $r}^2+2\right)}-\frac{1}{3 \left(t^2 \text{$\omega $r}^2+2\right)^2}+\frac{2 \tan ^{-1}\left(\frac{t \text{$\omega $r}}{\sqrt{2}}\right) \left(\sqrt{\frac{2}{3}} t \text{$\omega $r}+\left(-\frac{31}{24}+\frac{4}{\sqrt{3} \pi }+\frac{\sqrt{\pi } \Gamma \left(\frac{2}{3}\right)}{\Gamma \left(\frac{1}{6}\right)}\right)\right)}{\pi }+\frac{31}{24}
        
% can put a 1.03 in the arctan and drop the frac error from 0.0127 to 0.0116
lambda= 31/24 ...
    - (1/3)./( (2 + t.^2 * omega_rad^2 ).^2 ) ...
    - (5/12)./(2 + t.^2 * omega_rad^2) ...
    + atan((t.*omega_rad)/sqrt(2))*(2/pi)...
        .*(     sqrt(2/3).*t.*omega_rad + ...
                -(31/24) ...
                +4/(sqrt(3)*pi)  ...
                +(sqrt(pi)*gamma(2/3))/gamma(1/6)  ...
               );
     
           

lambda=repmat(lambda,[1,3]);


end